services:
  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      - TZ=Asia/Shanghai
      - MARIADB_ROOT_PASSWORD=r00tp4ssw0rd
      - MARIADB_AUTO_UPGRADE=1 # 自动升级数据库
      - MARIADB_DISABLE_UPGRADE_BACKUP=1 # 禁用升级备份以节省空间
    volumes:
      - mariadb_data:/var/lib/mysql # 数据持久化
      - mariadb_config:/etc/mysql/conf.d:ro
      - mariadb_logs:/var/log/mysql
      - mariadb_init:/docker-entrypoint-initdb.d:ro
    ports:
      - 6033:3306
    restart: always
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --innodb_flush_log_at_trx_commit=2
      --innodb_flush_method=O_DIRECT
      --query_cache_type=1
      --query_cache_size=32M
      --slow_query_log=1
      --slow_query_log_file=/var/log/mysql/slow.log
      --long_query_time=2

volumes:
  mariadb_data:
    driver: local
  mariadb_config:
    driver: local
  mariadb_logs:
    driver: local
  mariadb_init:
    driver: local
